spring:
  profiles:
    active: development
  application:
    name: random
  redis:
    host: localhost
    port: 6379

  datasource:
    dynamic:
      primary: life #设置默认的数据源或者数据源组
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源
      datasource:
        life:
          url: jdbc:mysql://150.158.82.218:3306/life?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
          username: linHe
          password: yqcMysql_2023
        composer:
          url: jdbc:mysql://150.158.82.218:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
          username: linHe
          password: yqcMysql_2023

server:
  port: 8806